from .bnn import PynqBNN, CnvClassifier, LfcClassifier, RUNTIME_HW, RUNTIME_SW
from .bnn import NETWORK_CNVW1A1, NETWORK_CNVW1A1_INTERLEAVED, NETWORK_CNVW1A1_RESILIENT_INTERLEAVED, NETWORK_CNVW1A1_TMR, NETWORK_CNVW1A2, NETWORK_CNVW1A2_INTERLEAVED, NETWORK_CNVW1A2_RESILIENT_INTERLEAVED, NETWORK_CNVW1A2_RESILIENT_INTERLEAVED, NETWORK_CNVW2A2, NETWORK_CNVW2A2_INTERLEAVED, NETWORK_CNVW2A2_RESILIENT_INTERLEAVED, NETWORK_CNVW2A2_TMR, NETWORK_LFCW1A1, NETWORK_LFCW1A2, NETWORK_LFCW1A2_INTERLEAVED, available_params
import bnn.faults as faults
import bnn.util as util

__version__ = 0.1
